#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Wayfire

WALLPAPER='/home/ghost/Pictures/wallpapers/mocha.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
